namespace Praxis.Data;

/// <summary>
/// Constant values associated with SQL server
/// </summary>
public sealed class SqlServerConstants {

	/// <summary>
	/// Error number that is generated by SqlServer when a unique constraint violation occurs
	/// <para>Includes primary key</para>
	/// <para>2627</para>
	/// </summary>
	public const int UNIQUECONSTRAINTERRORNUMBER = 2627;

	/// <summary>
	/// Error number that is generated by SqlServer when a unique index violation occurs
	/// <para>2601</para>
	/// </summary>
	public const int UNIQUEINDEXERRORNUMBER = 2601;

	/// <summary>
	/// Error number used when raising an error number in a TSQL statement where a user defined message is present
	/// <para>Remember -- you can specify state numbers as well to use in conjunction with the message</para>
	/// </summary>
	public const int USERRAISEDERRORNUMBER = 50000;
}